### ISSUE TITLE
Xcode resports errors and fails to build "PIA VPN" scheme

### ISSUE THREAD

**Issue by t0mmar** [pia-foss/mobile-ios#2]
# Summary

### Steps to reproduce
Building from scratch as described in the README file.

### What is the current bug behaviour?
Xcode reports errors and fails to build "PIA VPN" scheme.

### What is the expected correct behaviour?
Xcode should successfully build the app when build directions are followed.

### Relevant logs and/or screenshots
```
Showing Recent Messages
:-1: /Users/tom/Projects/vpn-ios/Pods/Target Support Files/Pods-PIA VPN Tunnel/Pods-PIA VPN Tunnel.debug.xcconfig: unable to open file (in target "PIA VPN Tunnel" in project "PIA VPN") (in target 'PIA VPN Tunnel')
```
<img width="1594" alt="screen shot 2018-12-14 at 6 09 38 pm" src="https://user-images.githubusercontent.com/45108654/50036064-7fa89a00-ffcb-11e8-8dd2-9ea444423179.png">

### Possible fixes suggested re-mediation
The error is complaining about a missing file: Pods-PIA VPN Tunnel.debug.xcconfig
That file is indeed missing on the filesystem.

If this is a private file with secrets, can you update the build instructions explaining what should go in that file and provide a dummy file with example values that result in a successful build?

Or is the error possibly caused by the spaces in the PATH?

### Assignees and labels
( please add labels as applicable )    

- [ ] Patched
- [ ] Verified patch

**Comment by ueshiba** [comment]
Hello @t0mmar !

Thanks for your message, could you try to run the following commands, hopefully that should fix your issue:

`pod deintegrate`
`pod install`

Regards,
Jose Blaya

**Comment by thomasmarkiewicz** [comment]
Hi @ueshiba,

I just cloned latest and tried `pod deintegrate` as you suggested.

`pod install` fails for me on OpenSSL step `Installing OpenSSL-Apple (1.1.0h)`.  This was likely happening before and I just have not noticed.

Any idea how to fix this?

```
Building openssl-1.1.0h for MacOSX 10.14 i386...
  Logfile: /Users/tom/Library/Caches/CocoaPods/Pods/Release/OpenSSL-Apple/1.1.0h-cd153/bin/MacOSX10.14-i386.sdk/build-openssl-1.1.0h.log
  Configure...
  Make (using 8 thread(s))...
Problem during make - Please check /Users/tom/Library/Caches/CocoaPods/Pods/Release/OpenSSL-Apple/1.1.0h-cd153/bin/MacOSX10.14-i386.sdk/build-openssl-1.1.0h.log
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5295k  100 5295k    0     0  11.4M      0 --:--:-- --:--:-- --:--:-- 11.3M
```

Log file attached...

[build-openssl-1.1.0h.log](https://github.com/pia-foss/vpn-ios/files/2752530/build-openssl-1.1.0h.log)

**Comment by ueshiba** [comment]
Hi @t0mmar 

> The problem is compiling the openssl framework with the current version of Xcode and support iOS9 at the same time. (you need the iOS9 SDK installed in the computer).

The quick solution is to change the deployment target to iOS11+ 

If you need to compile your app for old versions, you can follow the solution described in this issue https://github.com/pia-foss/tunnel-apple/issues/66

I hope this can help you to resolve the issue.

Thank you,
Jose Blaya
