### ISSUE TITLE
Feature Request: Support for tvOS17

### ISSUE THREAD

**Issue by dtantono** [pia-foss/mobile-ios#28]
Hi
tvOS17 will support VPN. Will PIA support tvOS as well?

https://www.apple.com/uk/newsroom/2023/06/tvos-17-brings-facetime-and-video-conferencing-to-apple-tv-4k/

**Comment by kp-said-rehouni** [comment]
> Hi tvOS17 will support VPN. Will PIA support tvOS as well?
> 
> https://www.apple.com/uk/newsroom/2023/06/tvos-17-brings-facetime-and-video-conferencing-to-apple-tv-4k/

Thank you for your feature request @dtantono. We are excited to announce there will be a tvOS version soon. 
Stay tuned!
