### ISSUE TITLE
Hotspot Helper causes Wi-Fi network to not connect for 45 seconds

### ISSUE THREAD

**Issue by Markko** [pia-foss/mobile-ios#5]
# Summary
When connecting to a captive portal hotspot, the Wi-Fi will try to connect for 45 seconds before showing the captive portal, regardless of settings in the app.

### Steps to reproduce
 - Install the app
- connect to an insecure captive portal wi-fi network  ( eg. starbucks ) 

### What is the current bug behaviour?
connection to the network takes ~45 seconds

### What is the expected correct behaviour?
captive portal interface should be shown

**Comment by ueshiba** [comment]
Hello Markko, thanks for the ticket. We will take a look and fix the issue.

**Comment by kp-laura-sempere** [comment]
Hi @Markko , apologies for the late response.

We have updated the repo to the latest version. Can you verify whether this problem still persists on the latest update?
Thanks a lot!

**Comment by Markko** [comment]
@kp-laura-sempere unfortunately I no longer have access to the devices I was using to create this issue.
